### Aula 1:

**Algebra Linear**: Resolver sistemas de esquações lineares.

### Aula 2:

Se você utilizar 4 cifrões você pode escrever fórmulas matemáticas em Markdown, conforme esse exemplo abaixo:

$$\alpha + \beta = 10$$

In [1]:
# Principais bibliotecas que trabalham com estatística:
import numpy as np
import scipy as sc
import sympy as sy 

--------------

In [2]:
x1 = 2 # Valor escalar
x2 = np.array([1,2,3]) # Vetor com três elementos escalares
x3 = np.array([[1],[2],[3]]) # Matriz com três elementos vetores com elementos escalares
x4 = np.array([[1,2,3],[1,2,3],[1,2,3]]) # Matriz tradicional

In [3]:
print('Escalar: \n', x1)
print('Vetor: \n', x2)
print('Matriz: \n', x3)
print('Matriz Tradicional: \n', x4)

Escalar: 
 2
Vetor: 
 [1 2 3]
Matriz: 
 [[1]
 [2]
 [3]]
Matriz Tradicional: 
 [[1 2 3]
 [1 2 3]
 [1 2 3]]


### Aula 3:

In [4]:
import pandas as pd

In [5]:
lista = [1,2,3,4,5]

df = pd.DataFrame({'coluna 1':lista})
df

coluna 1
0         1
1         2
2         3
3         4
4         5

In [6]:
type(df)

pandas.core.frame.DataFrame

### Aula 4:

-----------

Soma de Matrizes: Utiliza a propriedade de distributiva conforme exemplo abaixo:

In [12]:
x1+x2

array([3, 4, 5])

In [13]:
x2+x3

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

### Aula 5:

Multiplicar Matrizes: Somente ocorre se o **numero de colunas** da primeira matriz deve ser **igual** ao **numero de linhas** da segunda matriz.

Lembrando que a ordem dos fatos da multiplicação altera o resultado no caso de matrizes, ou seja: **A.B != B.A**

In [11]:
x4@x3

array([[14],
       [14],
       [14]])

Divisão Matrizes:

**A.X = Y** --> Essa equação é muito importante para solucionar diversos problemas de Machine Learning (Equação Fundamental da Algebra Linear)

Podemos até conseguir dividir matrizes, porém não podemos passa por exemplo a matriz solução X dividindo pela matriz resultado Y.

In [14]:
x4/x3

array([[1.        , 2.        , 3.        ],
       [0.5       , 1.        , 1.5       ],
       [0.33333333, 0.66666667, 1.        ]])